salesforcecli/plugin-lightning-dev

command-snapshot.json
messages/lightning.preview.component.md
messages/lightning.preview.org.md
messages/lightning.preview.site.md
package.json
schemas/lightning-preview-component.json
schemas/lightning-preview-org.json
schemas/lightning-preview-site.json
src/commands/lightning/preview/component.ts
src/commands/lightning/preview/org.ts
src/commands/lightning/preview/site.ts
test/commands/lightning/preview/component.nut.ts
test/commands/lightning/preview/component.test.ts
test/commands/lightning/preview/org.nut.ts
test/commands/lightning/preview/org.test.ts
test/commands/lightning/preview/site.nut.ts
test/commands/lightning/preview/site.test.ts

Update the lightning-dev plugin with initial command stubs.
[@W-15469593@](https://gus.lightning.force.com/a07EE00001oEFwSYAW)

feat: add initial command stubs

---

package.json
src/commands/lightning/preview/site.ts
src/shared/orgUtils.ts
src/shared/prompt.ts
yarn.lock

Update the preview command to use new lwr local dev setup api. Added additional core interactions for downloading the site and updating the site proxy locally.
@W-15469642@ @W-15428953@

feat: preview site command updates

---

src/lwc-dev-server/index.ts

To be merged after #52 is merged.
It passes the Identity token to the LWC Dev Server

Pass Identity token to LWC Dev Server

---

.github/workflows/test.yml
package.json
test/commands/lightning/preview/app.nut.ts
test/commands/lightning/preview/component.nut.ts
test/commands/lightning/preview/site.nut.ts
yarn.lock

CI builds are currently failing b/c CI uses the non-active LTS version of node during build which the repo does not support. This PR updates the build jobs to exclude non-active LTS version of node by using the `UT_DISABLE_NODE_CURRENT` environment variable.
@W-16114966@

Disable current node version

---

.github/workflows/test.yml

Enable running CI jobs on PRs from forks
@W-15906501@

ci: run tests on pull requests from forks

---

.vscode/tasks.json
package.json
test/lwc-dev-server/index.e2e.test.ts
test/shared/previewUtils.test.ts

- Commented out the test in index.e2e.test.ts that calls lwc-dev-server's stopServer(), since that's erroneously exiting the calling process and making all the tests "pass", whether they're successful or not.
- Fixed tasks.json to call our existing test compilation, so we can run tests from VSCode.
@W-16207529@ - Issues with test runs always succeeding, even with failures.

@W-16207529@ fix: shoring up test running functionality

---

messages/lightning.preview.app.md
messages/shared.utils.md
src/commands/lightning/preview/app.ts
src/configMeta.ts
src/lwc-dev-server/index.ts
src/shared/configUtils.ts
src/shared/previewUtils.ts
test/commands/lightning/preview/app.test.ts
test/lwc-dev-server/index.e2e.test.ts
test/lwc-dev-server/index.test.ts
test/shared/configUtils.test.ts
test/shared/previewUtils.test.ts

* Saves identity data structure in `sf`'s config
* Saves identity token on server
@W-15428971@

feat: save identity data to sf's config and to the server

---

.github/workflows/test.yml
src/shared/configUtils.ts
src/shared/previewUtils.ts
test/shared/previewUtils.test.ts

Remove `0.` from launch params for mobile scenarios
@W-16273178@

fix: remove 0. for mobile launch params

---

.github/workflows/create-github-release.yml

Update the create-github-release action to only publish on demand for now. This will avoid unintentional publishes until we are ready for the official release of the plugin
@W-16499669@

chore: only trigger release on demand

---

.github/workflows/onRelease.yml

Attempting to setup CI for publishing. CTC causes npm publish to be skipped currently, so seeing if this will fix it for us.
@W-16499669@

chore: setup CI for npm publish

---

README.md
package.json
src/commands/lightning/dev/site.ts
yarn.lock

- Adds some authentication support
- Fixes missing dependency issues on site startup
- Disable CSR Data Preload for core lwr sites
@W-16557123@ @W-16449290@ @W-16647062@

feat: [sites] local dev authentication

---

README.md
package.json
src/commands/lightning/dev/site.ts
src/shared/experience/expSite.ts
yarn.lock

- On local-dev startup, simulate the auth flow for establishing a valid SID token for sites via servlets (`/servlet/networks/switch`). Grab the valid token from those requests and append to any proxied requests back to core for the life of the local development session. Requests in the browser may still show asGuest=true but be proxied to your org with valid authentication credentials by the dev server. 
- Create a new environment variable `SITE_GUEST_ACCESS`. When set to true, this will skip attempting to establish a valid authentication session at startup and allow you to access the site as a guest user. 
**Note: This is more of a temporary solution to support sites auth and may evolve as we update the Beta and work towards GA**  
@W-16647027@

feat: establish valid experience site sessions at startup

---

messages/lightning.dev.app.md
messages/shared.utils.md
src/commands/lightning/dev/app.ts
src/commands/lightning/dev/site.ts
src/shared/orgUtils.ts
test/commands/lightning/dev/app.test.ts

Update the `lightning:dev:app` command to first check and see whether Local Dev is enabled for an org or not before proceeding with the local preview.
@W-16591156@

feat: ensure local dev is enabled for an org

---

messages/prompts.md
src/shared/previewUtils.ts
src/shared/promptUtils.ts
test/commands/lightning/dev/app.test.ts
test/shared/previewUtils.test.ts

If no value is provided for the flag `--device-id` then interactively prompts the user to select a mobile device.
@W-16911876@

feat: prompt user to select mobile device

---

messages/prompts.md
src/commands/lightning/dev/app.ts
src/shared/orgUtils.ts
src/shared/previewUtils.ts
src/shared/promptUtils.ts
test/commands/lightning/dev/app.test.ts
test/shared/orgUtils.test.ts

What does this PR do?
If no value is provided for the flag `--name` then interactively prompts the user to select a lightning experience app.
What issues does this PR fix or reference?
@W-16599797@

feat: prompt user to select lightning experince app

---

.husky/check-versions.cjs
.husky/check-versions.js
.husky/pre-commit
messages/shared.utils.md
package.json
src/commands/lightning/dev/app.ts
src/commands/lightning/dev/site.ts
src/shared/orgUtils.ts
test/commands/lightning/dev/app.test.ts

Ensure that the org API version is supported by the local dev server.
@W-16974125@

feat: add api version validation

---

package.json
src/lwc-dev-server/index.ts
test/lwc-dev-server/index.test.ts
yarn.lock

We consider lwc folders under each package directory in this format: `<package-directory>/**/lwc`.
```
force-app/main/default/lwc
force-app/main/customer360/lwc
force-app/test/default/lwc
package/lwc
```
@W-16844177@
Fixes https://github.com/salesforcecli/plugin-lightning-dev/issues/185, https://github.com/salesforcecli/plugin-lightning-dev/issues/174, #212

fix: consider lwc dirs nested under package directories

---

.github/workflows/create-github-release.yml
.github/workflows/onRelease.yml
.github/workflows/test.yml
.github/workflows/validate-pr.yml
CONTRIBUTING.md
package.json

Backports https://github.com/salesforcecli/plugin-lightning-dev/pull/203

fix: backporting the workflow scripts to 252-patch @W-16974485@

---

.github/workflows/onRelease.yml
.github/workflows/test.yml
.github/workflows/validate-pr.yml

fix: set node version for npm-publish @W-16974485@

---

src/commands/lightning/dev/site.ts

Add environment variables for testing the plugin:
- SETUP_ONLY - sets up a site and skips server startup
- PORT - allows you to specify a port to launch the server on
[@W-15440520@](https://gus.lightning.force.com/a07EE00001nuOXkYAM)

feat: add setup_only / port env variables

---

src/commands/lightning/dev/site.ts

Add env variable to skip opening the browser during CI testing.
@W-15440520@

feat: add open_browser env var for testing

---

.github/README.md
.github/workflows/onRelease.yml
.github/workflows/test.yml
README.md
package.json
yarn.lock

- Backport node 22+ support to 252-patch
[@W-17310811@](https://gus.lightning.force.com/a07EE000026024WYAQ)

feat(backport): support node 22+

---

.github/workflows/create-github-release.yml
.github/workflows/onRelease.yml
.github/workflows/test.yml
.github/workflows/validate-pr.yml
package.json

Mark 254-patch branch as release branch with version settings.
@W-17311538@
BREAKING CHANGE: this version works with 256(summer25) release and newer

feat!: new minor release for spring25(254/patch) branch @W-17311538@

---

LICENSE.txt
command-snapshot.json
messages/lightning.dev.site.md
messages/prompts.md
package.json
src/commands/lightning/dev/site.ts
src/shared/experience/expSite.ts
src/shared/promptUtils.ts
test/spec/expSite.test.ts
yarn.lock

- feat: add cli parameter to force refresh of locally cached site
- fix: bug causing sites with basePaths to not render correctly
- fix: auth related proxy issues for sites
- fix: Site preview not working with unpublished sites. Default API generation to use publish site shape until fixed in future patch release.
- chore: update LWR to v0.16.2
- doc: update cli text indicating sites is still in Beta
- doc: better error message handling
@W-17046400@ @W-17312145@ @W-17178650@
fixes: #199

feat: [sites] add `get-latest` cli parameter / update lwr -> v0.16.2 (includes latest local-dev fixes)

---

package.json
src/shared/experience/expSite.ts
yarn.lock

- Allow users to specify a SID token that they've generated in their browser and use that for proxying authentication requests
@W-17758477@

fix: @W-17758477 cli accepts a provided sid token for use during sites local dev

---

src/commands/lightning/dev/site.ts

- Fix for issue with commerce sites not properly reloading on module changes
@W-17792692@

fix: @W-17792692 - internal developer scenarios

---

CONTRIBUTING.md

- Update plugin release instructions to clarify release process
[@W-18658526@](https://gus.lightning.force.com/a07EE00002FFg8bYAD)

chore: update plugin release instructions @W-18658526

---

CONTRIBUTING.md

BREAKING CHANGE: this version works with 258(winter26) release and newer
[@W-18658526@](https://gus.lightning.force.com/a07EE00002FFg8bYAD)

fix!: trigger npm publish (v4.0.0) @W-18658526

---

.github/workflows/create-github-release.yml
.github/workflows/onRelease.yml
.github/workflows/test.yml
package.json

- Create prerelease version for 256-patch
[@W-18658526@](https://gus.lightning.force.com/a07EE00002FFg8bYAD)

feat: 256-patch prerelease (v3) @W-18658526

---

src/commands/lightning/dev/component.ts

Allow component command to skip opening the browser based on environment variable
[@W-18851168@](https://gus.lightning.force.com/a07EE00002GjHorYAF)

feat(component): add open browser option based on environment variable @W-18851168

---

command-snapshot.json
messages/lightning.dev.app.md
messages/lightning.dev.site.md
messages/shared.utils.md
package.json
src/commands/lightning/dev/app.ts
src/commands/lightning/dev/site.ts
src/shared/experience/expSite.ts
src/shared/previewUtils.ts
test/commands/lightning/dev/app.test.ts
yarn.lock

Launches site in preview URL
@W-18283821@

feat: launch site preview @W-18283821@

---

package.json
yarn.lock

W-19293277: bump version number on next
