salesforcecli/plugin-lightning-dev

.husky/pre-commit, .husky/pre-push, .vscode/settings.json, package.json, tsconfig.json, yarn.lock
Add lwr dependencies to the cli repo
[@W-15428922@](https://gus.lightning.force.com/a07EE00001nnGsvYAE)
=> feat: add lwr packages / fix commit hooks

CHANGELOG.md, README.md, command-snapshot.json, package.json, src/commands/hello/world.ts
Updates the plugin name for the repository to be "plugin-lightning-dev"
[@W-15428922@](https://gus.lightning.force.com/a07EE00001nnGsvYAE)
=> feat: update repository name

.github/workflows/failureNotifications.yml
Disable automatic slack notifications on publish failure
[@W-15428922@](https://gus.lightning.force.com/a07EE00001nnGsvYAE)
=> fix: publish failure slack notifications

.git2gus/config.json
Update git2gus product tag
[@W-15428922@](https://gus.lightning.force.com/a07EE00001nnGsvYAE)
=> chore: update git2gus product tag

package.json
Set node engine < 22 due to pwa-kit restrictions
@W-15748312@
=> chore: update node engine

package.json, src/commands/lightning/preview/app.ts, src/lwc-dev-server/index.ts, yarn.lock
Removes unused fields in `ServerConfig`.
@W-16116624@
=> feat: bump LWC to v9.0.0 @W-16116624

src/commands/lightning/preview/app.ts, src/shared/previewUtils.ts, test/shared/configUtils.test.ts, test/shared/orgUtils.test.ts, test/shared/previewUtils.test.ts
Add more test coverage for `PreviewUtils` + fix 3 failing tests in `ConfigUtils`
@W-15961505@
=> Add more test coverage

package.json, yarn.lock
Bumps LWC to 9.3.0
@W-15818699@
=> fix: bump LWC version to 9.3.0

package.json, yarn.lock
Upgrade latest lwr and lwc versions
=> chore: upgrade to latest lwr / lwc

.github/workflows/test.yml
Skip Typescript dependency check
@W-16273178@
=> ci: skip typescript dep check

package.json, yarn.lock
Pull in latest `lwc-dev-mobile-core` to have the latest updated for generating self-signed certificate.
@W-16273178@
=> chore: pull in latest lwc-dev-mobile-core

package.json, yarn.lock
Fix issues with sfdx-module-provider failing to find local source when SFDX project not up to date with org
@W-16353180@ @W-16327451@
=> fix: [sites] sfdx-module-provider fails to find src

package.json, src/commands/lightning/dev/site.ts, src/shared/experience/expSite.ts, src/shared/orgUtils.ts, src/shared/prompt.ts, yarn.lock
When an experience site has been published, a new static resource becomes available for use with local development. This PR prompts the user if they would like to update their local site setup with the package available in the org, or continue with what they have already downloaded.
@W-16450430@
=> feat: update site bundles locally after publish

.github/workflows/create-github-release.yml, PLUGIN_TEMPLATE.md, README.md, command-snapshot.json, messages/lightning.dev.app.md, messages/lightning.dev.site.md, package.json, src/commands/lightning/dev/app.ts, src/commands/lightning/dev/site.ts, test/commands/lightning/dev/site.test.ts
Cleanup commands based on feedback from CLI teams
@W-16286173@ [W-16286173](https://gus.lightning.force.com/lightning/r/a07EE00001x36FrYAI/view)
=> feat: remove unused command flags / update readme

README.md
[@W-16701114@](https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE0000210LXoYAM/view) Fixes broken links in README, caught by `link-check`
=> fix(readme): broken links in README.md

README.md
Fix issues link in our readme to point at this repository
@W-16702478@
=> chore: update issues link in README.MD

.github/ISSUE_TEMPLATE/Bug_report.md
Update the bug template to include salesforce CLI version information
N/A
=> chore: update bug template [skip-ci]

package.json, yarn.lock
- Addresses a bug where some windows environments were returning 404s for site resources
- Upgrades lwr to 0.14.3
@W-16791496@
=> fix: sites not rendering on windows  / upgrade lwr v0.14.3

.github/workflows/create-github-release.yml, .github/workflows/onRelease.yml, CONTRIBUTING.md, package.json
BREAKING CHANGE: this version works with 254(spring25) release and newer
@W-16974485@
=> feat!: 254 code line cut over, main now tracks 254(spring25) codeline @W-16974485@

.github/workflows/onRelease.yml
Fixes release workflow by adding a missing required param
@W-16974485@
=> fix: add runs-on property to release workflow @W-16974485@

package.json, yarn.lock
Update the main branch to latest LWR alpha release
[@W-15440507@](https://gus.lightning.force.com/lightning/r/a07EE00001nuJwJYAU/view)
=> feat: upgrade to latest lwr

.git2gus/config.json
Update git2gus product tag
[@W-16286173@](https://gus.lightning.force.com/a07EE00001x36FrYAI)
=> chore: Update product tag in git2gus configuration

package.json
Add yarn version to volta config.
[@W-16974408@](https://gus.lightning.force.com/a07EE000023JHtmYAG)
=> chore: add yarn version to volta

package.json
Bumps target API version to 63.0 to track main
@W-17117927@
=> fix: bump target API version to 63.0 to match main codeline

.github/workflows/onRelease.yml, .github/workflows/test.yml
=> fix: set node version for npm-publish @W-16974485@

package.json, yarn.lock
Upgrade LWR to v0.15.0-alpha.44
[@W-15469602@](https://gus.lightning.force.com/a07EE00001oE62qYAC)
=> chore: upgrade lwr - v0.15.0-alpha.44

package.json, yarn.lock
Update lwc dependencies to match 254/patch code line
Prepares the main branch for CLCO
@W-17311538@
=> feat: update lwc dependencies to match 254/patch code line @W-17311538@

.github/README.md, .github/workflows/onRelease.yml, .github/workflows/test.yml, package.json, yarn.lock
- Update LWR to support node 22+ (v0.15.6)
- Re-enable CI test workflows for the entire cli supported set of node versions [current, lts, lts-1]
@W-17385983@
=> feat: support node 22+

package.json
release 252-patch fixes
@W-15440507@
=> fix: release 252-patch

package.json, yarn.lock
Update lwc dependency version to match core's spring25 branch
fixes an error that is logged in the browser console
@W-17663897@
=> chore: update lwc oss dependency to 8.10.3 to match spring25 @W-17663897

LICENSE.txt, package.json, yarn.lock
=> chore: update lwc dependencies to match summer25 release @W-17663897

package.json, yarn.lock
- upgrade lwr -> v0.16.3
- address authentication cookie issues
- address commerce b2b store issues
- fix issues switching between authenticated / guest user context
@W-17722994@
fixes #199
=> fix: W-17722994 lwr v0.16.3 ->  addresses auth cookie issues

src/lwc-dev-server/index.ts, yarn.lock
Bumps LWC deps to 11.1.2 and passes absolute directories to LWC Dev server, it doesn't work with relative directories.
@W-17705190@
=> W-17705190 hot reload not working on windows

command-snapshot.json, messages/lightning.dev.component.md, messages/prompts.md, package.json, src/commands/lightning/dev/component.ts, src/commands/lightning/dev/site.ts, src/shared/promptUtils.ts, yarn.lock
This PR introduces a new CLI command that launches a LWR development environment enabling developers to rapidly iterate on Lightning Web Components (LWC) in isolation with hot module replacement (HMR).
@W-17889507@
=> @W-17889507 initial single component preview

package.json, yarn.lock
Upgrading LWR to pull in latest changes for component preview
@W-17889805@
=> fix: @W-17889805 bump lwr version

README.md, package.json, yarn.lock
- Fixes babel error when running single component preview
@W-17910486@
=> fix: @W-17910486 babel error during single component preview

.github/workflows/onRelease.yml
Now that R2 is out, prerelease should be promoted to latest.
@W-17949916@
=> fix: bump version 2 to latest @W-17949916@

.github/workflows/onRelease.yml
- backport release script changes
@W-17949916@
=> fix: [backport] bump version 2 to latest @W-17949916

.github/workflows/create-github-release.yml, .github/workflows/onRelease.yml, .github/workflows/test.yml, package.json
- Update main branch to v4
[@W-18658526@](https://gus.lightning.force.com/a07EE00002FFg8bYAD)
=> feat!: new major release (v4.0.0) @W-18658526

.github/workflows/automerge.yml
Fix automerge scheduled runs for dependabot
[@W-18658547@](https://gus.lightning.force.com/a07EE00002FFdgwYAD)
=> chore: update automerge workflow to use squash merge method @W-18658547

test/projects/sfdx-lwc-project/force-app/main/default/classes/AccountCardController.cls, test/projects/sfdx-lwc-project/force-app/main/default/classes/AccountCardController.cls-meta.xml, test/projects/sfdx-lwc-project/force-app/main/default/lwc/accountCard/accountCard.css, test/projects/sfdx-lwc-project/force-app/main/default/lwc/accountCard/accountCard.html, test/projects/sfdx-lwc-project/force-app/main/default/lwc/accountCard/accountCard.js, test/projects/sfdx-lwc-project/force-app/main/default/lwc/accountCard/accountCard.js-meta.xml
Add some example lwc code / apex controller for testing + demos
[@W-18658547@](https://gus.lightning.force.com/a07EE00002FFdgwYAD)
=> test: example lwc code + apex controller @W-18658547

package.json, yarn.lock
Bump LWC to 13.0.27
@W-18283826@
=> fix: bump LWC @W-18283826

.cursorrules, .vscode/tasks.json
Update build task and add cursor rules for repo
@W-18979277@
=> chore: update build task and add cursor rules for repo @W-18979277

package.json, yarn.lock
Upgrade lwc-dev-server to include proper trusted origins for salesforce domains
[@W-19097047@](https://gus.lightning.force.com/a07EE00002Ie5IrYAJ)
=> fix: update LWC dependencies to version 13.0.31 @W-19097047

package.json, yarn.lock
Remove base components package as its no longer needed for single component preview
@W-19437012@
=> fix: remove base components package @W-19437012
